definitions:
  todos.Todo:
    description: Todo model
    properties:
      completed:
        type: boolean
      description:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Backend Todo API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Todo API
  version: "1.0"
paths:
  /api/ping:
    get:
      consumes:
      - application/json
      description: Healt Check
      produces:
      - text/plain
      responses:
        "200":
          description: 'Ok - alias api versión: x.y.z'
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      security:
      - OAuth2AccessCode: []
      summary: Ping
      tags:
      - ping
  /api/todos:
    get:
      consumes:
      - application/json
      description: Get Todo
      produces:
      - application/json
      responses:
        "200":
          description: Todo
          schema:
            $ref: '#/definitions/todos.Todo'
        "404":
          description: Not found
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get Todo
      tags:
      - Todos
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-API-KEY
    type: apiKey
swagger: "2.0"
